# Generated by Django 5.1.1 on 2024-09-27 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_suma_alter_course_trainer_alter_courses_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suma',
        ),
    ]
