# Generated by Django 5.1.1 on 2024-09-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_course_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_id',
        ),
    ]
