# Generated by Django 5.1.1 on 2024-09-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_remove_course_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
