# Generated by Django 5.1.1 on 2024-10-02 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
